apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: nodejs-api
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: nodejs-api
    spec:
      osType: linux
      containers:
        - name: api
          securityContext:
            runAsUser: 1001
          image: TARGET_DOCKER_REGISTRY/example-app-nodejs-api:VERSION
          imagePullPolicy: Always
          resources:
            cpu:
              required: 150m
            memory:
              required: 256Mi
          ports:
            - name: http
              value: 8080
              containerPort: 8080
              type: tcp
