apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-app-nodejs-at
  annotations:
    version: 0.0.1
    description: "Acceptance Test runner for the example-app-nodejs-at"
spec:
  components:
    - componentName: todo-api-at
      parameterValues:
        - name: target
          value: "nodejs-api"

